---
- name: Deploy Configs
  hosts: {{ cookiecutter.in.avd.fabric_name }}
  gather_facts: false
  tasks:

    - name: Deploy Configurations to Devices
      import_role:
        name: arista.avd.eos_config_deploy_eapi
